security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
          #  http_basic:
           #     realm: "These url needs Admin permission"
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                 path:   /login
                 
    access_control:
        - { path: ^/admin|product, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext